name: Python Application Workflow

on:
  push:
    branches:
      - main  # or any other branch you want to trigger the workflow
  pull_request:
    branches:
      - main  # or any other branch you want to trigger the workflow

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install streamlit python-dotenv openai python-docx

    - name: Run script
      env:
        api_key: ${{ secrets.APIKEY }}
      run: |
        python prompt.py
